apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cidstore-writer
  namespace: cidtree
spec:
  serviceName: cidstore-rest
  replicas: 1
  selector:
    matchLabels:
      app: cidstore-writer
  template:
    metadata:
      labels:
        app: cidstore-writer
    spec:
      containers:
        - name: cidstore
          image: cidstore:latest
          ports:
            - containerPort: 8000
            - containerPort: 5557
            - containerPort: 5558
            - containerPort: 5559
          envFrom:
            - configMapRef:
                name: cidstore-config
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "0.5"
              memory: 1Gi
