"""
This type stub file was generated by pyright.
"""

import ast

"""
annotation_constraints.py

Implements the AST transformation described in spec-07-Annotation-Constraints.md:
Rewrites any Call inside a type annotation as Annotated[BaseType, MetaExpr].
"""
class AnnotateCallsTransformer(ast.NodeTransformer):
    """
    AST transformer that rewrites any Call inside a type annotation as
    Annotated[BaseType, MetaExpr], as described in ZVIC spec-07.
    """
    def __init__(self) -> None:
        ...
    
    def visit_FunctionDef(self, node: ast.FunctionDef): # -> FunctionDef:
        ...
    
    def visit_Module(self, node: ast.Module) -> ast.Module:
        ...
    


def apply_annotation_constraints(source: str) -> str:
    """
    Applies the AnnotateCallsTransformer to the given Python source code string.
    Returns the transformed source as a string.
    """
    ...

