name: CI (Free-threaded + Compatibility)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-python:
    name: Build CPython (Ubuntu)
    runs-on: ubuntu-latest
    timeout-minutes: 120
    outputs:
      artifact-path: "/opt/python3.13-ff"
    steps:
      - uses: actions/checkout@v4

      - name: Setup cache dir
        run: mkdir -p $HOME/.cache/python-src

      - name: Restore built-interpreter cache
        id: python-cache-restore
        uses: actions/cache@v4
        with:
          path: /opt/python3.13-ff
          key: python3-ff-${{ runner.os }}-3.13.7

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
            libreadline-dev libsqlite3-dev wget curl llvm libncursesw5-dev libgdbm-dev \
            libnss3-dev libffi-dev liblzma-dev libxml2-dev libxmlsec1-dev

      - name: Build CPython 3.13.7
        if: steps.python-cache-restore.outputs.cache-hit != 'true'
        run: |
          chmod +x scripts/ci_build_python.sh
          scripts/ci_build_python.sh 3.13.7 /opt/python3.13-ff $(nproc) $HOME/.cache/python-src

      - name: Save built-interpreter to cache
        if: steps.python-cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: /opt/python3.13-ff
          key: python3-ff-${{ runner.os }}-3.13.7

      - name: Archive built interpreter
        uses: actions/upload-artifact@v4
        with:
          name: python3.13-ff
          path: /opt/python3.13-ff

  test-free-threaded:
    name: Test (free-threaded build)
    runs-on: ubuntu-latest
    needs: build-python
    steps:
      - uses: actions/checkout@v4

      - name: Download built interpreter
        uses: actions/download-artifact@v4
        with:
          name: python3.13-ff

      - name: Add built Python to PATH
        run: echo "$(pwd)/python3.13-ff/bin" >> $GITHUB_PATH

      - name: Verify built Python
        run: |
          python -V
          python -c "import sys; print('supports_free_threading=', hasattr(sys, '_is_gil_enabled'))"

      - name: Install pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with free-threading + JIT
        run: |
          python -X gil=0 -X jit=1 -m pytest tests/ -q

  compatibility-matrix:
    name: Compatibility checks (system Python matrix)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install deps (system Python)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run quick compatibility tests
        run: |
          python -m pytest tests/test_python313_features.py -q
